site_name: DeskGap

strict: true
repo_url: https://github.com/patr0nus/DeskGap
edit_uri: edit/master/docs

docs_dir: ./api

theme:
  name: 'material'
  font: false
  palette:
    primary: 'white'

extra_css:
  - 'assets/styles.css'

markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite
  - toc:
      permalink: True
